apiVersion: apps/v1
kind: Deployment
metadata:
  name:  {{ .Value.fastapi }}
spec:
  selector:
    matchLabels:
      app: {{ .Value.fastapi }}
  replicas: 2
  template:
    metadata:
      labels:
        app: {{ .Value.fastapi }}
    spec:
    containers:
      - name:  {{ .Value.fastapi }}
        image: "{{ .Value.image.repository }}: {{ .Value.image.tag}}"
        ports:
        - containerPort: {{ .Value.service.targetport }}
        envFrom:
          name: myconfigmapv1.0
    restartPolicy: OnFailure
