apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.fastapi }}
spec:
  selector:
    app: {{ .Values.fastapi }}
  replicas: 2
  type: {{ .Values.service.type }}
  ports:
  - port: {{ .Values.service.port }}
    targetPort: {{ .Values.service.targetport }}
