# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pytest

    - name: Debug tree
      run: |
        pwd
        ls -R

    - name: Test with pytest
      run: |
        export PYTHONPATH=$PWD
        pytest -v

    - name: Log in to Docker hub
      uses: docker/login-action@v3
      with:
        username: ${{ vars.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    
    - name: Build Docker image
      uses: docker/build-push-action@v6
      with:
        load: true
        tags: |
          track_processing:test
          ${{ vars.DOCKERHUB_USERNAME}}/${{ github.event.repository.name }}:latest

    - name: Running Container
      run: |
        docker run -d --name track_test -p 8000:8000 track_processing:test
        sleep 5

    - name: Debug containers
      run: |
        docker ps -a 

    - name: Debug container
      run: |
        docker logs track_test

    - name: Docker health check
      run: |
        curl -f http://localhost:8000/health

    - name: Cleanup
      run: |
        docker stop track_test
        docker rm track_test

    - name: Push Docker image
      run: |
        docker push ${{ vars.DOCKERHUB_USERNAME}}/${{ github.event.repository.name }}:latest
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Setup Kubectl
      uses: azure/setup-kubectl@v3

    - name: Setup Helm√ü
      uses: azure/setup-helm@v4

    - name: Create kind cluster
      uses: helm/kind-action@v1
      with:
          cluster_name: kind

    - name: Debug kind
      run: |
        kind get clusters
        kubectl get nodes
    
    - name: Docker run
      run: |
        docker pull ${{ vars.DOCKERHUB_USERNAME}}/${{ github.event.repository.name }}:latest
        kind load docker-image ${{ vars.DOCKERHUB_USERNAME}}/${{ github.event.repository.name }}:latest

    - name: Install helm package
      run: |
          helm upgrade --install track chart/ \
          --set image.repository=${{ vars.DOCKERHUB_USERNAME}}/${{ github.event.repository.name }} \
          --set image.tag=latest

    - name: Testing
      run: |
        kubectl port-forward svc/track_processing 8000:80
        sleep 5
        curl -f http://localhost:8000/health
        

        